'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Download,Play,Save,Sparkles,Undo2,X} from 'lucide-react';
import LatexCodeEditor from './latex-code-editor';
import ResumePdfPreview from './resume-pdf-preview';
import {LatexEngine} from '../lib/latex-engine';
import {ResumeDraft} from '../lib/resume';
import {Optimization,applyChanges,validateOptimization} from '../lib/resume-changes';
import {clientHeaders} from '../lib/identity';

function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
export default function ResumeStudio({initial,onClose}:{initial:ResumeDraft;onClose:()=>void}){
 const [source,setSource]=useState(initial.latex),[saved,setSaved]=useState(initial.latex),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [auto,setAuto]=useState(true),[compiling,setCompiling]=useState(false),[compiled,setCompiled]=useState(''),[pdfUrl,setPdfUrl]=useState(''),[log,setLog]=useState(''),[compileError,setCompileError]=useState('');
 const [aiReady,setAiReady]=useState(false),[aiChecked,setAiChecked]=useState(false),[optimizing,setOptimizing]=useState(false),[instruction,setInstruction]=useState('Emphasize the experience most relevant to this job. Make the bullets clearer and more concise.'),[report,setReport]=useState<Optimization|null>(null),[reportSource,setReportSource]=useState(''),[undo,setUndo]=useState<{before:string;after:string}|null>(null),[reportApplied,setReportApplied]=useState(false),[importText,setImportText]=useState('');
 const engine=useRef<LatexEngine|null>(null),running=useRef(false),alive=useRef(true),latest=useRef(source),pdf=useRef<Uint8Array|null>(null),url=useRef('');
 latest.current=source;
  useEffect(()=>{engine.current=new LatexEngine();alive.current=true;fetch('/api/resumes/optimize',{headers:clientHeaders()}).then(r=>r.json()).then((d:any)=>{if(alive.current){setAiReady(d.available);setAiChecked(true);}}).catch(()=>{if(alive.current)setAiChecked(true);});return()=>{alive.current=false;engine.current?.close();if(url.current)URL.revokeObjectURL(url.current);};},[]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(source!==saved){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[source,saved]);
 async function compile(){if(running.current)return;running.current=true;setCompiling(true);setCompileError('');const snapshot=latest.current;try{const result=await engine.current!.compile(snapshot,message=>{if(alive.current)setLog(message);});if(!alive.current)return;setLog(result.log);if(snapshot!==latest.current)return;pdf.current=result.pdf;const next=URL.createObjectURL(new Blob([new Uint8Array(result.pdf)],{type:'application/pdf'}));if(url.current)URL.revokeObjectURL(url.current);url.current=next;setPdfUrl(next);setCompiled(snapshot);}catch(e){if(alive.current&&snapshot===latest.current){const message=e instanceof Error?e.message:'Compilation failed';setCompileError(message);setLog(message);}}finally{running.current=false;if(alive.current)setCompiling(false);}}
 useEffect(()=>{if(!auto||compiling||source===compiled||compileError)return;const timer=setTimeout(()=>void compile(),1200);return()=>clearTimeout(timer);},[source,auto,compiling,compiled,compileError]);
 function edit(value:string){setSource(value);setCompileError('');}
 async function save(){setSaving(true);setError('');const snapshot=latest.current;try{const r=await fetch('/api/resumes',{method:'POST',headers:{'Content-Type':'application/json',...clientHeaders()},body:JSON.stringify({jobId:initial.jobId,latex:snapshot})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setSaved(snapshot);setNotice('Draft saved.');}catch(e){setError(e instanceof Error?e.message:'Saving failed.');}finally{setSaving(false);}}
 function close(){if(source!==saved&&!window.confirm('Close without saving your latest edits?'))return;onClose();}
 async function optimize(){setOptimizing(true);setError('');setReport(null);setReportApplied(false);const snapshot=source;try{const r=await fetch('/api/resumes/optimize',{method:'POST',headers:{'Content-Type':'application/json',...clientHeaders()},body:JSON.stringify({jobId:initial.jobId,latex:snapshot,instruction})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setReport(validateOptimization(d,snapshot));setReportSource(snapshot);}catch(e){setError(e instanceof Error?e.message:'Optimization failed.');}finally{setOptimizing(false);}}
 function apply(){if(!report||source!==reportSource)return;try{const next=applyChanges(source,report.changes);setUndo({before:source,after:next});edit(next);setReportApplied(true);setNotice(`Applied ${report.changes.length} changes. Review the PDF, then save.`);}catch(e){setError((e as Error).message);}}
 function repair(){const before=source,after=source.replace('\\newcommand{\\resumeItem}[1]{\\item #1}','\\newcommand{\\resumeItem}[1]{\\par\\noindent #1\\par\\vspace{2pt}}');setUndo({before,after});edit(after);setNotice('Fixed the old template’s list command. Resume wording is unchanged.');}
 function copyPrompt(){const prompt=`Optimize this resume for ${initial.company}: ${initial.role}. ${instruction}\nReturn JSON only: {"summary":"...","changes":[{"before":"exact unique LaTeX substring","after":"replacement","reason":"what changed and why"}],"warnings":[]}. Use non-overlapping exact replacements. Do not invent skills, dates, claims or metrics.\nLATEX:\n${source}`;navigator.clipboard.writeText(prompt).then(()=>setNotice('Prompt copied. Include the job description in your AI chat, then paste its JSON report below.')).catch(()=>setError('Clipboard unavailable. Download the .tex file to use in your AI chat.'));}
 return <Dialog open onOpenChange={open=>{if(!open)close();}}><DialogContent className="resume-studio" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}>
  <header className="studio-heading"><div><span className="eyebrow">RÉSUMÉ STUDIO / {initial.company}</span><DialogTitle>Make every line count.</DialogTitle><DialogDescription>{initial.role}</DialogDescription></div><button aria-label="Close résumé studio" className="button secondary" onClick={close}><X size={18}/></button></header>
  <div className="studio-toolbar"><button className="button primary" disabled={compiling} onClick={compile}><Play size={15}/>{compiling?'Compiling…':'Recompile'}</button><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto compile</label><button className="button secondary" disabled={saving} onClick={save}><Save size={16}/>{saving?'Saving…':'Save'}</button><button className="button secondary" disabled={!pdfUrl||source!==compiled||compiling} onClick={()=>download(new Blob([new Uint8Array(pdf.current!)],{type:'application/pdf'}),`Kirtan-Rajesh-${initial.company.replace(/[^a-z0-9]/gi,'-')}.pdf`)}><Download size={16}/>PDF</button><button className="button secondary" onClick={()=>download(new Blob([source],{type:'text/plain;charset=utf-8'}),'resume.tex')}>Download .tex</button><span role="status">{source===saved?'Saved':'Unsaved edits'} · {source===compiled?'Preview up to date':pdfUrl?'Preview needs compilation':'Waiting for preview'}</span></div>
  {error&&<div className="studio-message error" role="alert">{error}</div>}{notice&&<div className="studio-message" role="status">{notice}</div>}
  {source.includes('\\newcommand{\\resumeItem}[1]{\\item #1}')&&<div className="studio-message">This saved draft uses an older template with an invalid list command. <button onClick={repair}>Fix template</button></div>}
  <div className="studio-workspace"><section className="studio-source"><div className="studio-pane-title"><strong>main.tex</strong><span>LaTeX · Ctrl/Cmd+S to save</span></div><LatexCodeEditor value={source} onChange={edit} onSave={save}/></section><section className="studio-preview"><div className="studio-pane-title"><strong>PDF preview</strong><span>{compiling?'Typesetting…':'pdfLaTeX'}</span></div>{compileError&&<div className="compile-error" role="alert"><strong>Compilation failed</strong><p>{compileError.split('\n').filter(x=>x.startsWith('!')||x.startsWith('l.')).slice(0,4).join('\n')||compileError.slice(0,220)}</p><small>Fix the source and recompile. The last successful preview is retained.</small></div>}{pdfUrl?<ResumePdfPreview data={pdf.current!}/>:<div className="preview-empty"><strong>{compiling?'Typesetting your résumé…':'Your PDF will appear here'}</strong><p>The first compile downloads public TeX packages. Your document compiles in this browser.</p></div>}<details className="compile-log"><summary>Compilation log</summary><pre>{log||'No compilation output yet.'}</pre></details></section>
  <aside className="studio-ai"><div className="studio-pane-title"><strong><Sparkles size={16}/>{aiReady?'AI editor':'Resume reviewer'}</strong></div><div className="studio-ai-body"><label>What should improve?<textarea aria-label="Optimization instruction" rows={4} maxLength={2000} value={instruction} onChange={e=>setInstruction(e.target.value)}/></label><button className="button primary" disabled={!aiChecked||optimizing} onClick={optimize}><Sparkles size={16}/>{optimizing?'Reviewing your draft…':aiReady?'Optimize with AI':'Review with job evidence'}</button><p className="ai-status">{!aiChecked?'Checking optimizer…':aiReady?'AI compares this draft with the job description and returns exact, reviewable edits.':'Local review is ready: it uses verified profile facts and job keywords. Connect OpenAI later for deeper wording suggestions.'}</p>
  {report&&<section className="change-report"><h3>{reportApplied?'What changed':report.mode==='local'?'Local evidence review':'Suggested changes'}</h3><p>{report.summary}</p>{report.changes.map((c,i)=><article key={i}><strong>{i+1}. {c.reason}</strong><small>BEFORE</small><pre className="change-before">{c.before}</pre><small>AFTER</small><pre className="change-after">{c.after}</pre></article>)}{report.warnings.length>0&&<><h4>Still needs your attention</h4><ul>{report.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></>}{!reportApplied&&<button className="button primary" disabled={!report.changes.length||source!==reportSource} onClick={apply}>Apply {report.changes.length} changes</button>}{!reportApplied&&source!==reportSource&&<p>The draft changed. Optimize again to avoid overwriting your edits.</p>}</section>}
  {undo&&<button className="button secondary" disabled={source!==undo.after} onClick={()=>{edit(undo.before);setUndo(null);setReportApplied(false);setNotice('Restored the draft before the last update.');}}><Undo2 size={16}/>Undo last update</button>}
  <details className="chat-workflow"><summary>Use an AI chat instead</summary><p>Copy the draft prompt into your AI chat. Paste its JSON change report here to review and apply exact edits.</p><button className="button secondary" onClick={copyPrompt}>Copy optimization prompt</button><textarea aria-label="AI change report JSON" rows={5} value={importText} onChange={e=>setImportText(e.target.value)} placeholder={'{"summary":"…","changes":[],"warnings":[]}'}/><button className="button secondary" onClick={()=>{try{const parsed=JSON.parse(importText.replace(/^```(?:json)?\s*|\s*```$/g,''));setReport(validateOptimization(parsed,source));setReportSource(source);setReportApplied(false);setError('');}catch(e){setError((e as Error).message);}}}>Review AI changes</button></details><p className="ai-status">Review every claim before applying. Optimization cannot guarantee shortlisting.</p></div></aside></div>
 </DialogContent></Dialog>;
}
