import {Job,Source,plain,safeUrl} from './jobs';
async function json(url:string){const r=await fetch(url,{headers:{Accept:'application/json'},redirect:'manual',signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`Source returned HTTP ${r.status}`);return r.json() as Promise<any>;}
export async function fetchSource(s:Source):Promise<{jobs:Job[];complete:boolean}>{
 const collected=new Date().toISOString();let jobs:Job[]=[];
 if(!/^[a-zA-Z0-9_-]{1,80}$/.test(s.board))throw Error('Invalid board name');
 const base={source:s.id,company:s.company,collected,pay:''};
 if(s.provider==='greenhouse'){const d=await json(`https://boards-api.greenhouse.io/v1/boards/${s.board}/jobs?content=true`);if(!Array.isArray(d.jobs))throw Error('Unexpected job feed');jobs=d.jobs.map((j:any)=>({...base,id:`${s.id}:${j.id}`,title:j.title,location:j.location?.name||'',url:safeUrl(j.absolute_url),description:plain(j.content),posted:j.updated_at||null,dateLabel:'Source updated'}));}
 else if(s.provider==='ashby'){const d=await json(`https://api.ashbyhq.com/posting-api/job-board/${s.board}?includeCompensation=true`);if(!Array.isArray(d.jobs))throw Error('Unexpected job feed');jobs=d.jobs.filter((j:any)=>j.isListed!==false).map((j:any)=>({...base,id:`${s.id}:${j.id}`,title:j.title,location:[j.location,...(j.secondaryLocations||[]).map((l:any)=>l.location)].join(' · '),url:safeUrl(j.jobUrl||j.applyUrl),description:plain(j.descriptionPlain||j.descriptionHtml),posted:j.publishedAt||null,dateLabel:'Published',pay:j.compensation?.compensationTierSummary||''}));}
 else if(s.provider==='lever'){const d=await json(`https://api.lever.co/v0/postings/${s.board}?mode=json`);if(!Array.isArray(d))throw Error('Unexpected job feed');jobs=d.map((j:any)=>({...base,id:`${s.id}:${j.id}`,title:j.text,location:j.categories?.location||'',url:safeUrl(j.hostedUrl),description:plain([j.descriptionPlain,...(j.lists||[]).map((x:any)=>x.text+'\n'+x.content),j.additionalPlain].join('\n')),posted:j.createdAt?new Date(j.createdAt).toISOString():null,dateLabel:'Posted',pay:j.salaryDescriptionPlain||''}));}
 else {let total=0;for(let offset=0;offset<300;offset+=100){const d=await json(`https://www.amazon.jobs/en/search.json?base_query=software+development+engineer&loc_query=India&country=IND&offset=${offset}&result_limit=100&sort=recent`);if(!Array.isArray(d.jobs)||d.error)throw Error('Amazon search unavailable');total=Number(d.hits)||0;jobs.push(...d.jobs.filter((j:any)=>j.country_code==='IND').map((j:any)=>({...base,id:`amazon:${j.id_icims}`,title:j.title,location:j.location,url:safeUrl('https://www.amazon.jobs'+j.job_path),description:plain(j.description+'\nBasic qualifications\n'+j.basic_qualifications+'\nPreferred qualifications\n'+j.preferred_qualifications),requirements:plain(j.basic_qualifications),posted:j.posted_date||null,dateLabel:'Posted'})));if(d.jobs.length<100)break;}return {jobs,complete:total<=300};}
 return {jobs:jobs.filter(j=>j.url),complete:true};
}
