import {Job,Profile,plain,assess} from './jobs';
export type ResumeDraft={id:string;jobId:string;company:string;role:string;latex:string;createdAt:string;updatedAt:string;source:string};
export const resumeFacts={name:'Kirtan Rajesh',email:'kirtanrajesh1@gmail.com',phone:'+91-9422102188',education:'B.Tech. Computer Science and Engineering (AI & Robotics), Vellore Institute of Technology, Chennai | 2021--2025 | CGPA 8.72/10',experience:[
 ['Cybage Software','Software Developer - AI Solutions Engineer | Feb 2026 -- Present','Built production RAG and Advanced RAG pipelines using hybrid retrieval, query rewriting and re-ranking over FAISS; integrated AWS Bedrock and LiteLLM multi-model routing.\nBuilt async FastAPI services backed by PostgreSQL and Redis with Langfuse observability, cutting API latency 40% and deployment failures 30%.'],
 ['Hucenrotia Lab, NYCU','Research Intern - Robotics & AI | Aug 2025 -- Oct 2025','Built a real-time MuJoCo perception-to-prediction-to-control pipeline in C++ and Python using an Extended Kalman Filter, reaching 77.8% interception accuracy at 18ms mean compute.'],
 ['Caliber Interconnect','Software Developer Intern | Jun 2024 -- Jul 2024','Built a real-time React and WebSocket robot-control dashboard over ROSBridge; refactored component architecture and reduced dashboard load time 35%.']],
 projects:[['EMIOS - Enterprise Migration Intelligence Platform','Python, LangGraph, AWS Bedrock, Qdrant, Neo4j, PostgreSQL, FastAPI','Architected a 12-agent LangGraph pipeline for automated cloud-migration assessment, grounded with RAG over architecture documents and live SSE output. Built a Neo4j digital twin, NetworkX failure analysis and Monte Carlo risk forecasting; deployed containerized on AWS EC2.'],['Wellkept - AI Native Healthcare Platform','FastAPI, Gemini, pgvector, React Native','Shipped a production web and iOS AI document pipeline with Gemini Vision OCR, structured biomarkers and per-user RAG over PostgreSQL/pgvector; built async SQLAlchemy, Redis/Celery and shared REST APIs for 100K active-user scale.']],
 publications:['Deep Reinforcement Learning for Urban Air Quality Management - IEEE Access 2025','MSHAN: Multi-Scale Hybrid Attention Network for ECG Arrhythmia Detection - IEEE ICCCNT 2025','Resilient Solar Microgrid Management via Multi-Agent RL - Results in Engineering, Elsevier 2025']};
function esc(s:string){return s.replace(/\\/g,'\\textbackslash{}').replace(/[&%$#_{}]/g,m=>`\\${m}`).replace(/\^/g,'\\textasciicircum{}').replace(/~/g,'\\textasciitilde{}');}
function keywords(j:Job){const raw=plain(j.description).toLowerCase();const known=['python','c++','java','sql','fastapi','postgresql','redis','docker','aws','react','rag','langgraph','pytorch','tensorflow','machine learning','git','rest','data structures','algorithms','mongodb','celery','kubernetes','go','typescript','spring','kafka'];return known.filter(k=>raw.includes(k));}
export function makeResume(job:Job,p:Profile):ResumeDraft{const k=assess(job,p).matched.map(x=>x.toLowerCase()), fitFacts=[...resumeFacts.experience,...resumeFacts.projects].filter(x=>k.some(word=>`${x[0]} ${x[1]} ${x[2]}`.toLowerCase().includes(word)));const skills=Array.from(new Set([...k,...p.skills.map(x=>x.toLowerCase())].filter(x=>k.includes(x)||p.skills.some(y=>y.toLowerCase()===x))));const summary=`Software developer with production experience building backend services and AI systems. Strong in ${skills.slice(0,7).join(', ')||'Python, APIs and data structures'}.`;const section=(title:string,items:string[])=>`\\section{${title}}\n${items.map(x=>`\\resumeItem{${x.startsWith('\\textbf')?x:esc(x)}}`).join('\n')}`;const latex=`\\documentclass[10pt]{article}\n\\usepackage[margin=0.55in]{geometry}\n\\usepackage[hidelinks]{hyperref}\n\\usepackage{enumitem}\n\\usepackage{titlesec}\n\\pagenumbering{gobble}\n\\setlist[itemize]{leftmargin=*,noitemsep,topsep=1pt}\n\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]\n\\newcommand{\\resumeItem}[1]{\\par\\noindent #1\\par\\vspace{2pt}}\n\\begin{document}\n\\begin{center}{\\LARGE\\textbf{${esc(resumeFacts.name)}}}\\\\${esc(resumeFacts.phone)} $\\cdot$ \\href{mailto:${resumeFacts.email}}{${esc(resumeFacts.email)}} $\\cdot$ India\\end{center}\n\\small\n${section('SUMMARY',[summary])}\n${section('EXPERIENCE',resumeFacts.experience.flatMap(x=>[`\\textbf{${esc(x[0])}} - ${esc(x[1])}`,...x[2].split('\n')]))}\n${section('SELECTED PROJECTS',resumeFacts.projects.flatMap(x=>[`\\textbf{${esc(x[0])}} | ${esc(x[1])}`,x[2]]))}\n${section('EDUCATION',[resumeFacts.education])}\n${section('PUBLICATIONS',resumeFacts.publications)}\n${section('SKILLS',[skills.join(', ')])}\n\\end{document}`;return {id:`resume:${job.id}`,jobId:job.id,company:job.company,role:job.title,latex,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),source:'Generated from verified résumé facts'};}
